'use strict';
const map = {
  0: "RZRESULT_SUCCESS",
  5: "RZRESULT_ACCESS_DENIED",
  6: " RZRESULT_INVALID_HANDLE",
  50: "RZRESULT_NOT_SUPPORTED",
  87: "RZRESULT_INVALID_PARAMETER",
  1062: "RZRESULT_SERVICE_NOT_ACTIVE",
  1152: "RZRESULT_SINGLE_INSTANCE_APP",
  1167: "RZRESULT_DEVICE_NOT_CONNECTED",
  1168: "RZRESULT_NOT_FOUND",
  1235: "RZRESULT_REQUEST_ABORTED",
  1247: "RZRESULT_ALREADY_INITIALIZED",
  4309: "RZRESULT_RESOURCE_DISABLED",
  4319: "RZRESULT_DEVICE_NOT_AVAILABLE",
  5023: "RZRESULT_NOT_VALID_STATE",
  259: "RZRESULT_NO_MORE_ITEMS",
  2147500037: "RZRESULT_FAILED"
};

const parseErr = function (n) {
  switch (n) {
    case -1: return "RZRESULT_INVALID";
    default: return map[n];
  }
};

module.exports = {
  parseErr
};